### ISSUE TITLE
build.cmd not working (Can't download files from sourceforge)

### ISSUE THREAD

**Issue by UnrealKaraulov** [VerySleepy/verysleepy#110]
build.cmd not working (Can't download files from sourceforge)

**Comment by CyberShadow** [comment]
Which file is failing to download? Please post your logs.

**Comment by UnrealKaraulov** [comment]
> Which file is failing to download? Please post your logs.

```
build.cmd: Building Dr. MinGW
drmingw_build: Found 7-Zip at "C:\Program Files\7-Zip\7z.exe"
Downloading i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z...
Downloading https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.3.0/threads-win32/dwarf/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z/download
  c:\Users\Admin\Downloads\verysleepy-master\thirdparty\/mingw/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z
Исключение при вызове "DownloadFile" с "2" аргументами: "Невозможно соединиться с удаленным сервером"
строка:1 знак:1
+ (New-Object Net.WebClient).DownloadFile('https://sourceforge.net/proj ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

```

**Comment by CyberShadow** [comment]
It works for me. It's possible that SourceForge is selecting a mirror that isn't working for you. Please try again or maybe try using a proxy or VPN in case it's some kind of routing issue.

If it's a connection issue you could try diagnosing it with: `curl -v -L -O https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.3.0/threads-win32/dwarf/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z/download`.

**Comment by UnrealKaraulov** [comment]
> `curl -v -L -O https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.3.0/threads-win32/dwarf/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z/download`.

```

c:\Users\Admin\Downloads\verysleepy-master>curl
curl: try 'curl --help' for more information

c:\Users\Admin\Downloads\verysleepy-master>curl -v -L -O https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.3.0/threads-win32/dwarf/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z/download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.18.11.128...
* TCP_NODELAY set
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0* Connected to sourceforge.net (104.18.11.128) port 443 (#0)
* schannel: SSL/TLS connection with sourceforge.net port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 186 bytes...
* schannel: sent initial handshake data: sent 186 bytes
* schannel: SSL/TLS connection with sourceforge.net port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with sourceforge.net port 443 (step 2/3)
* schannel: encrypted data got 1077
* schannel: encrypted data buffer: offset 1077 length 4096
* schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - Функция отзыва не смогла произвести проверку отзыва для сертификата.
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
* Closing connection 0
* schannel: shutting down SSL/TLS connection with sourceforge.net port 443
* schannel: clear security context handle
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - Функция отзыва не смогла произвести проверку отзыва для сертификата.

```
Bad SSL certificate?

**Comment by CyberShadow** [comment]
Ah, I see it uses your OS certificate store (PowerShell would as well). This can happen if your OS trusted root certificate store is out of date. I'm not sure how to fix that, maybe ensure you're using a recent version of Windows and all updates from Windows Update are installed?

**Comment by CyberShadow** [comment]
Here was a similar error (due to TLS version support): https://github.com/VerySleepy/verysleepy/issues/82#issuecomment-875363315

**Comment by UnrealKaraulov** [comment]
I tried but can't fix it :(

This is unfixable error ?( No alternative sources to download this files ?

**Comment by CyberShadow** [comment]
You could try downloading the file with a web browser to the mingw directory, and build.cmd will use the existing file.

**Comment by UnrealKaraulov** [comment]
> You could try downloading the file with a web browser to the mingw directory, and build.cmd will use the existing file.

I can't do it, can't found needed files in sourceforge. Maybe blocked in my country?

**Comment by CyberShadow** [comment]
It's the same link, just open it in Firefox or something.

**Comment by UnrealKaraulov** [comment]
> It's the same link, just open it in Firefox or something.

Nothing, file not found.

**Comment by CyberShadow** [comment]
Just to be clear, are we talking about this link?

https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.3.0/threads-win32/dwarf/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z/download

When I open it in a web browser, I get a webpage which starts a download after 5 seconds.

![image](https://user-images.githubusercontent.com/160894/216969981-b1c8b595-f412-432f-bcb6-78d5344ad9bb.png)

What do you get?

**Comment by UnrealKaraulov** [comment]
I get file not found, i can show my screenshot tonight

**Comment by UnrealKaraulov** [comment]
@CyberShadow after update windows to 11 preview, now no problems.
