### ISSUE TITLE
lazarus (free pascal) debug symbols

### ISSUE THREAD

**Issue by veksha** [VerySleepy/verysleepy#113]
verysleepy can't load symbols for Lazarus app, please help.
i choose Dwarf2:

![image](https://github.com/VerySleepy/verysleepy/assets/275333/2c139e4c-7f8d-478c-a697-0f2865875f10)

**Comment by CyberShadow** [comment]
Do you know if [Dr. MinGW](https://github.com/jrfonseca/drmingw/) can access the symbols?

**Comment by veksha** [comment]
how to check it?

<i>Dr. Mingw can read debugging information in DWARF format — generated by the Gnu C/C++ Compiler, and in a PDB file — generated by the Microsoft Visual C++ Compiler. It relies upon the [DbgHelp library](http://msdn.microsoft.com/en-us/library/windows/desktop/ms679294.aspx) to resolve symbols in modules compiled by the Microsoft tools. </i>

i guess it doesn't support fpc compiler?

BTW: if I select "Wine" in options. i see that symbols is trying to load, but very very very slow, and it ttakes forever and in the end app freezes.

**Comment by CyberShadow** [comment]
> how to check it?

I don't know. Maybe ask there?

> i guess it doesn't support fpc compiler?

I don't know. On one hand, DWARF is used by many languages and debuggers, and is supposed to be inter-compatible. On the other hand, there may be extensions or deviations from the spec that cause incompatibilities.

> BTW: if I select "Wine" in options. i see that symbols is trying to load, but very very very slow, and it ttakes forever and in the end app freezes.

That is interesting, but neither the Wine or Dr.MinGW implementations are developed in this repository, so there is probably not much we can do here other than collect information / forward it to the developers of those projects / update our version of these dependencies.

**Comment by veksha** [comment]
ok. thanks for info. closing for now.
