### ISSUE TITLE
Use stable sort for sorting columns in all functions list to preserve previous sort order

### ISSUE THREAD

**Issue by maks-a** [VerySleepy/verysleepy#24]
It may help to sort by time within modules.
For example, we can have time in descending order within modules.

           Time     Module
    Foo1    2.1      kernel32
    Foo2    1.9      kernel32
    Foo3    5.3      mydll
    Foo4    4.7      mydll

**Comment by CyberShadow** [comment]
197202eb81c176f713f05da2ab5609b8226e89a2 ?

**Comment by CyberShadow** [comment]
7964c9d829fa1729a1c6d484733a8e24e2794416 ?

**Comment by maks-a** [comment]
wow, that was fast. thank you.
