### ISSUE TITLE
Question: any directions on use the profiling core of verysleepy as API

### ISSUE THREAD

**Issue by hy9be** [VerySleepy/verysleepy#26]
Is it feasible to do the profiling programmatically in my own c++ application? Thanks!

**Comment by CyberShadow** [comment]
What exactly are you trying to achieve? Just have the results in memory? Save a .sleepy profile? GUI?

Very Sleepy is designed to profile other processes, so simply attempting to profile its own process would likely result in e.g. it suspending its own thread. There will probably be other complications. You could certainly try to reuse some code, but the code is not designed or structured for this

**Comment by hy9be** [comment]
Thanks! Yes as you said, I want to make a call from my application to generate profile data for itself. Sort of a self-diagnostics feature.

**Comment by CyberShadow** [comment]
If it's an option, perhaps the best way to do that is to hack off all GUI from Very Sleepy and invoke it as a separate process, passing your process's PID on its command line.

**Comment by hy9be** [comment]
Yes, that's what I am trying to do. Thanks!

**Comment by hy9be** [comment]
Btw @CyberShadow maybe a dummy question, I checked out the code and made a local build. But when the wx GUI launches, I was given an error saying cannot load dbghelpdr.dll. I only saw dbghelpms.dll in the repository. Any directions for troubleshooting?

**Comment by CyberShadow** [comment]
Yep, see here: https://github.com/VerySleepy/verysleepy#dr-mingw-dbghelp

**Comment by hy9be** [comment]
Thanks! I should have read that..
