### ISSUE TITLE
Installer blocked by antivirus

### ISSUE THREAD

**Issue by sorakun** [VerySleepy/verysleepy#27]
Avira says it contains unwanted program HEUR/APC (Cloud).

**Comment by CyberShadow** [comment]
It is a false positive from a heuristic algorithm:

http://www.avira.com/en/support-threats-description/tid/7815/tlang/en

Please report the false positive to the antivirus vendor.

**Comment by sorakun** [comment]
For some reason their upload form does not work, I get an upload error. I will see what I can do about it, in worst cases I'll mail them.
