### ISSUE TITLE
cannot find dbghelpdr.dll from a recent binary release of Very Sleepy

### ISSUE THREAD

**Issue by doneykoo** [VerySleepy/verysleepy#32]
According to the readme.md:
> If you do not want to build Dr. MinGW's DbgHelp from source, you can place dbghelpdr.dll from a recent binary release of Very Sleepy (or Dr. MinGW, where it will be called mgwhelp.dll) into the dbghelp_x86 and dbghelp_x64 directories appropriately.

But I cannot find dbghelpdr.dll from a recent binary release of Very Sleepy (0.90, nor 0.82)

**Comment by CyberShadow** [comment]
Sorry, that is only from 0.91 onwards... there are some binary releases posted in the issues here, e.g. [here](https://github.com/VerySleepy/verysleepy/issues/29#issuecomment-220884540).

**Comment by doneykoo** [comment]
thanks a lot @CyberShadow
