### ISSUE TITLE
Is "HELP" missing ???

### ISSUE THREAD

**Issue by aabatpurdue** [VerySleepy/verysleepy#34]
When I click on the "HELP" button, the only item in the drop down menu is an "About" button. 

Is there supposed to be anything else?

I note that there is a 'dbghelpms.dll" and a "dbghelpw.dll" dll in the "C:\Program Files\Very Sleepy CS\" folder.

--  Thanks,
--    Paul Townsend

**Comment by CyberShadow** [comment]
There is currently no built-in documentation.

The "help" in "dbghelp" does not relate to documentation.

**Comment by CyberShadow** [comment]
I've started a [GitHub project wiki](https://github.com/VerySleepy/verysleepy/wiki), which should cover the main functionality.

There is now a documentation entry in the "Help" menus, which open this wiki.

Hopefully that should be enough to improve the situation.
