### ISSUE TITLE
Symbol downloading woes

### ISSUE THREAD

**Issue by FGKD** [VerySleepy/verysleepy#35]
Several issues I am encountering when trying to download symbols:

- When running in non-admin mode, it tries to download, but doesn't actually download anything. When running in admin mode, it tries to download, and actually does. Reproducible. Maybe put something in the manifest so that on start, a UAC prompt shows up so it always runs in admin mode? Does this only happen on my system?
- Downloading is very slow. This is probably the fault of the Microsoft Symbol server.
- When downloading, sometimes the displayed % of the current file gets updated in the bottom text window, that's it. Would be nice to add a more verbose download monitor, with kb/s etc.
- When downloading, sometimes the currently downloaded file is displayed in the bottom text window. But sometimes nothing is displayed, although looking at my AppData/Local/sleepy Directory, I see new directories being created. Shouldn't these Directory/File names be displayed in the text window?
- When downloading, a window shows up "Downloading symbols...". 
  - The progress bar is only a constantly moving animation without information as there is probably no data set about current progress and 0%/100% values. Please provide data for the progress bar. 
  - The "Close" Button is greyed out, so you can't cancel the download. You have to close Very Sleepy, each time in a "Very Sleepy doesn't react, force close?" prompt. Please allow us to cancel and restart the downloading progress, as the servers often have hiccups.

**Comment by CyberShadow** [comment]
Hi,

> When running in non-admin mode, it tries to download, but doesn't actually download anything. When running in admin mode, it tries to download, and actually does. Reproducible. Maybe put something in the manifest so that on start, a UAC prompt shows up so it always runs in admin mode? Does this only happen on my system?

I don't think I've seen this problem. Perhaps try a different directory for the "local cache directory" option. It's also possible that that directory was created with permissions that only allow the administrator user to write to it.

> Downloading is very slow. This is probably the fault of the Microsoft Symbol server.
> When downloading, sometimes the displayed % of the current file gets updated in the bottom text window, that's it. Would be nice to add a more verbose download monitor, with kb/s etc.
> When downloading, sometimes the currently downloaded file is displayed in the bottom text window. But sometimes nothing is displayed, although looking at my AppData/Local/sleepy Directory, I see new directories being created. Shouldn't these Directory/File names be displayed in the text window?

Very Sleepy doesn't actually download symbols itself, this is done by Microsoft's dbghelp.dll. As such, it has very little control over presentation or performance.

> The progress bar is only a constantly moving animation without information as there is probably no data set about current progress and 0%/100% values. Please provide data for the progress bar.

As far as I know, dbghelp.dll doesn't provide symbol download progress in a machine-readable way. It does show a % in the debug log output, and it might be parseable and presentable as a progress bar, but it's an implementation detail that might change in future versions, and this would be essentially equivalent to screen-scraping.

**Comment by CyberShadow** [comment]
Could you please see if this issue occurs with the latest release:
https://github.com/VerySleepy/verysleepy/releases

As the latest release includes many fixes, it's likely that this particular problem was fixed as well. If you encounter further problems, please leave a comment or open a new issue. Thanks!

**Comment by FGKD** [comment]
Symbol download can still be slow and appear to hang, but as you already explained, there is nothing on your side that can be done about it, so being very patient even if the application appears to have become unresponsive has so far every time resulted in the download operation to end successfully after quite a while.
