### ISSUE TITLE
Filters cause wrong function highlight.

### ISSUE THREAD

**Issue by DEF7** [VerySleepy/verysleepy#41]
When filtering by module or source file (and possibly others) selecting a function from the list boxes in the Averages or Call Stacks tabs selects the wrong function in the main Functions list box.

Under the "Averages" tab when selecting a function name from the "Child Calls" listbox the wrong function is highlighted in the main "Functions" listbox. However, it does bring up the correct source code and shows the correct list of "Called From" functions - so it seems to know the right function being selected, just not the updated listbox entry index in the main Functions listbox. The same problem occurs when selecting a function from the list in the "Call Stacks" tab.

This does not happen when I have not enabled any filters, so it seems that it's simply ignoring all the functions that were filtered out as the function it does highlight in the main Functions listbox is always after the correct function, which to my mind indicates that the index is assuming the list is larger than what's being shown.

 This happens in both the 32 and 64 bit versions on my Windows 7 64-bit desktop - haven't  tested on any other machines yet.

 Otherwise VerySleepy is great! Thanks!

**Comment by CyberShadow** [comment]
Could you please see if this issue occurs with the latest release:
https://github.com/VerySleepy/verysleepy/releases

I believe this may have been fixed in https://github.com/VerySleepy/verysleepy/pull/58. If you encounter further problems, please leave a comment or open a new issue. Thanks!
