### ISSUE TITLE
Command line profiling doesn't import all symbols 

### ISSUE THREAD

**Issue by nolanhergert** [VerySleepy/verysleepy#51]
If I run 
`sleepy.exe /c foo.exe`, I get only the below symbols

![image](https://user-images.githubusercontent.com/377502/30673035-1ebcda20-9e25-11e7-9c73-c1969708f96f.png)

But if I run `sleepy.exe` and then select the process from the GUI, a lot more symbols show up. 

![image](https://user-images.githubusercontent.com/377502/30673007-ef76d2de-9e24-11e7-849d-68d738d0a08a.png)

The pictures aren't profiling the exact same time, but you get the idea. I'm trying to profile a 2-second-long program, so selecting the process from the GUI won't work very well anymore. Thanks!

**Comment by CyberShadow** [comment]
Can you provide the source code and/or an executable of an example program that exhibits this problem?

**Comment by nolanhergert** [comment]
Certainly, the above execution was from the latest eclipse installer, http://www.eclipse.org/downloads/eclipse-packages/

I have seen it work similarly with other programs.

Also, I am behind a corporate firewall with a proxy server. I haven't tested this behavior at home yet.

**Comment by CyberShadow** [comment]
Could you please see if this issue occurs with the latest release:
https://github.com/VerySleepy/verysleepy/releases

As the latest release includes many fixes, it's likely that this particular problem was fixed as well. If you encounter further problems, please leave a comment or open a new issue. Thanks!
