### ISSUE TITLE
Switch to Visual Studio Community 2017 

### ISSUE THREAD

**Issue by quijote** [VerySleepy/verysleepy#52]
Using Visual Studio 2010 has the following problems:
* It is not freely available from Microsoft. This makes it harder, for some people even impossible, to contribute to VerySleepy.
* It does not support modern C++

Visual Studio Community 2017 on the other hand is
* Free to download for everyone here: https://www.visualstudio.com/downloads/
* Has good support for C++ 11, 14 and 17: https://blogs.msdn.microsoft.com/vcblog/2017/05/10/c17-features-in-vs-2017-3/

The trunk version of WxWidgets compiles fine with VS 2017 using wx_vc15.sln

If support for Windows XP is absolutely required, there still seems to be a compatible toolset v141_xp in VS 2017.

**Comment by CyberShadow** [comment]
You can build Very Sleepy with Visual Studio 2010 through 2015 (any version which supports VS 2010 project/solution files). I haven't tested 2017.

Visual Studio has had free editions with C++ support for a long time, though I don't remember the first version to have it.

If there is problem here, it's certainly not as you've described it.

**Comment by CyberShadow** [comment]
> though I don't remember the first version to have it.

https://en.wikipedia.org/wiki/Microsoft_Visual_Studio_Express states that VS2005 was the first VS version to have a free Express edition.

**Comment by quijote** [comment]
You are right, there still seems to be an old version of VC Epxress 2010 available here: https://www.visualstudio.com/vs/older-downloads/

> You can build Very Sleepy with Visual Studio 2010 through 2015
Do you mean Visual Studio 2015 with platform toolset "Visual Studio 2015 (v140)"? Or VS 2015 but still using 2010 compiler (v100)? I wasn't able to compile yet with 2015 only.

**Comment by CyberShadow** [comment]
> I wasn't able to compile yet with 2015 only.

If you think it's something that can be fixed in the project (as opposed to a problem local to your machine or a bug in Visual Studio), please file an issue for that (or submit a pull request).

I don't see anything else to do in this issue, OK to close?
