### ISSUE TITLE
highlight selected call stack line in source display

### ISSUE THREAD

**Issue by grandinj** [VerySleepy/verysleepy#54]
it would be nice if the current selected frame/line in the call stack display, was highlighted in the source panel.
i.e. with a slightly different shade of background color on that line

**Comment by CyberShadow** [comment]
I think the behavior of source navigation was changed in https://github.com/VerySleepy/verysleepy/pull/58.

Could you please see if this request is still relevant with the latest release:
https://github.com/VerySleepy/verysleepy/releases

Please leave a comment or open a new issue if so. Thanks!

**Comment by grandinj** [comment]
ThankS!
