### ISSUE TITLE
Can we export the profiling data as .CSV in command line mode?

### ISSUE THREAD

**Issue by SBarik007** [VerySleepy/verysleepy#55]
I was using this software to profile one of my C++ component.It comes really handy in UI mode.But I wanted to run the process in the background and give me the details in `.CSV` format.As of now I able to generate a `.slpeey` file in command mode .How can I generate `.CSV`?

**Comment by CyberShadow** [comment]
Here is the current list of command-line options:

https://github.com/VerySleepy/verysleepy/blob/abfc85066dbd4e0b7aebf2f4ff924246ee73ddba/src/wxProfilerGUI/profilergui.cpp#L60-L71

**Comment by SBarik007** [comment]
Ok Thanks.Is the code available here is the updated one?And which version of visual studio is needed to build this code .

**Comment by CyberShadow** [comment]
> Is the code available here is the updated one?

Yes.

> And which version of visual studio is needed to build this code .

This is covered in the README:

https://github.com/VerySleepy/verysleepy#building

**Comment by SBarik007** [comment]
Thanks a ton .Have  a good day.

**Comment by SBarik007** [comment]
I was looking at creating a tool similar to yours,I wanted to know where shall I begin with.Do you have any blogs where we can refer for understanding the theory behind such tools.

**Comment by CyberShadow** [comment]
Maybe try starting from https://en.wikipedia.org/wiki/Profiling_(computer_programming)#Statistical_profilers .

**Comment by SBarik007** [comment]
I did set up Very Sleepy in my system.I am getting the below issues while trying to launch it.Any idea what could be the reason behind it?


15:34:02: Could not load dbghelpdr.dll: the specified module could not be found.
Dr. MinGW debug information will be unavailable.
15:34:02: Could not load dbghelpw.dll: unknown error c1
Wine debug information will be unavailable.
15:34:02: Could not load dbghelpw_wow64.dll: the specified module could not be found.
WoW64 Wine debug information will be unavailable.

**Comment by CyberShadow** [comment]
See the first paragraph of the build instructions:
https://github.com/VerySleepy/verysleepy#instructions

**Comment by SBarik007** [comment]
I have run that command before opening the project in Visual Studio,still seeing this error.

**Comment by CyberShadow** [comment]
Which command is that?

**Comment by SBarik007** [comment]
`git submodule update --init`

**Comment by CyberShadow** [comment]
Kindly review the documentation again. Updating submodules is not sufficient by itself.

**Comment by SBarik007** [comment]
Hi 
I am seeing some issue when dynamic threads get created in the runtime for the application under profile.

I started an application it had around 10 threads to begin with.I started the profiling the application.Now while performing the workflow in the application 5 more new threads got spawned.Now when I finish my profiling I see only methods for those 10 threads which was spawn initially. How can we get function names for all threads (Those spawn dynamically)?

**Comment by CyberShadow** [comment]
>  I am seeing some issue when dynamic threads get created in the runtime for the application under profile.
> 
> I started an application it had around 10 threads to begin with.I started the profiling the application.Now while performing the workflow in the application 5 more new threads got spawned.Now when I finish my profiling I see only methods for those 10 threads which was spawn initially. How can we get function names for all threads (Those spawn dynamically)?

We have an issue for that, please see here: https://github.com/VerySleepy/verysleepy/issues/4
