### ISSUE TITLE
Loading symbols from an incremental PDB

### ISSUE THREAD

**Issue by Yogurt4** [VerySleepy/verysleepy#56]
Hi,

When you have incremental linking enabled (/INCREMENTAL) and maybe /DEBUG:FASTLINK, VerySleepy cannot load the symbols at all, so only function addresses are displayed. Could there be an improvement for this?

Sometimes it's just necessary to profile a debug build, and incremental linking saves a lot of compilation/linking time.

**Comment by CyberShadow** [comment]
Probably, you just need a newer version of dbghelp.dll ?

Try replacing dbghelpms.dll with the latest one you have available (probably the one that came with the toolchain you used to create the PDB in question).

**Comment by Yogurt4** [comment]
Thank you, this really works.
It only took a while to get the proper versions. My VS 2017 has 10 instances of dbghelp.dll scattered around in various subdirectories.

**Comment by vegorovinno** [comment]
> 
> 
> Thank you, this really works.
> It only took a while to get the proper versions. My VS 2017 has 10 instances of dbghelp.dll scattered around in various subdirectories.

Can you tell which version works best?

I've tried placing various versions and Very Sleepy behavior ranges from 'hangs irrecoverably' to 'too slow to start profiling' (thread list update takes 4 seconds so clicks on Profile Selected are just ignored.

**Comment by vegorovinno** [comment]
Best version for me turned up in $:\Windows\System32\dbghelp.dll - no hangs and no missing symbols.

**Comment by CyberShadow** [comment]
Could you please see if this issue occurs with the latest release:
https://github.com/VerySleepy/verysleepy/releases

I believe someone contributed a fix (version bump of DbgHelp) which may address this particular problem. If you encounter further problems, please leave a comment or open a new issue. Thanks!
