### ISSUE TITLE
Does VerySleepy support static code  profiling?

### ISSUE THREAD

**Issue by BlessBei** [VerySleepy/verysleepy#61]
1、pull an engineering code to local on github
2、Analyze it through Very Sleepy.However, Very Sleepy can  open individual specific files, and cannot open the entire file for analysis.

**Comment by BlessBei** [comment]
I appreciate you help.
I mean:
I have a packaged project that It contains code files\UI files\.Batfile\.exe file.I just want to analyze the code file(static code profiling) and save as .csv

**Comment by BlessBei** [comment]
Does VerySleepy support static code profiling?

**Comment by CyberShadow** [comment]
No, Very Sleepy does not perform static instrumentation or any kind of static code analysis. It is a polling profiler only.
