### ISSUE TITLE
Could not load dbghelpdr.dll

### ISSUE THREAD

**Issue by casper** [VerySleepy/verysleepy#69]
I get this error when launching 0.91 on Windows Vista 32bit.

I downloaded DrMinGW 0.9.1 (also tried 0.9.2) and copied mgwhelp.dll into the Sleepy install folder + renamed it to dbghelpdr.dll, but I still get the same error.

Is there any way around this issue?
Thanks.

**Comment by CyberShadow** [comment]
Could you please see if this issue occurs with the latest release:
https://github.com/VerySleepy/verysleepy/releases

As the latest release includes many fixes, it's likely that this particular problem was fixed as well. If you encounter further problems, please leave a comment or open a new issue. Thanks!
