### ISSUE TITLE
Add filter by thread

### ISSUE THREAD

**Issue by aaalexandrov** [VerySleepy/verysleepy#70]
Currently, when multiple threads are selected for a profiling session, stats are displayed as an aggregate for all threads. When trying to profile a task system for example, you don't know in advance which thread will pick up the workload you're interested in profiling, so you can't select it beforehand.
The ability to filter by thread would alleviate the issue.

**Comment by CyberShadow** [comment]
I think we do not save which thread a sample came from in the profile file, so in order to fix this the profile file format would have to change first.

Currently no one is working on this software, but I will review and merge pull requests.
