### ISSUE TITLE
The latest build has been deleted from AppVeyor.

### ISSUE THREAD

**Issue by nicber** [VerySleepy/verysleepy#71]
This webpage https://ci.appveyor.com/project/CyberShadow/verysleepy/branch/master/artifacts
says:

Artifacts older than 6 months are automatically deleted.

**Comment by rmitton** [comment]
I've pushed a new build to AppVeyor. Please bear in mind Very Sleepy is very much in maintenance mode unless someone wants to step up and take charge of it.
