### ISSUE TITLE
What Visual Studio 2019 C++ settings work with VerySleepy? (No source files showing)

### ISSUE THREAD

**Issue by enjoysmath** [VerySleepy/verysleepy#72]
![image](https://user-images.githubusercontent.com/1606391/84581856-705e0480-ad9a-11ea-9728-766393aba91b.png)

Those are my current settings for x64 debug mode, or will it only work in x86 mode?

And all the other settings, what do *they* have to be?

Because I'm currently getting no source file showing for any of my executables line in the profiler % results.

**Comment by CyberShadow** [comment]
Could you please see if this issue occurs with the latest release:
https://github.com/VerySleepy/verysleepy/releases

I believe someone contributed a fix (version bump of DbgHelp) which may address this particular problem. If you encounter further problems, please leave a comment or open a new issue. Thanks!
