### ISSUE TITLE
Error: ProfilerExcep: ResumeThread failed.

### ISSUE THREAD

**Issue by lsalamon** [VerySleepy/verysleepy#73]
I have this message box:
Error: ProfilerExcep: ResumeThread failed.

I try to profile NT Service, 32 bit process, an run profiles at administrator rights.

How can I help to collect more information?

**Comment by CyberShadow** [comment]
Could you please see if this issue occurs with the latest release:
https://github.com/VerySleepy/verysleepy/releases

As the latest release includes many fixes, it's likely that this particular problem was fixed as well. If you encounter further problems, please leave a comment or open a new issue. Thanks!
