### ISSUE TITLE
Space missing in export to callgrind

### ISSUE THREAD

**Issue by LHolten** [VerySleepy/verysleepy#80]
Profiling gives me these times:
![profile](https://user-images.githubusercontent.com/24637999/98518139-476d6d00-226f-11eb-944e-295ec8083cb0.PNG)

But when I export as callgrind I get a file with these times
```
139 409381910
140 95989644778
141 2096919782
142 113953053157
144 1667677779
145 146053668132
146 2663961124269
147 41199119219
148 72730633928
154 9455466441082
155 192441989771
```

By comparing with the picture of the times in very sleepy I conclude that some values (or all values) are off by different powers of 10.

For example compare the lines 154 and 155, in very sleepy these are of the same order, but not in the exported file.

**Comment by LHolten** [comment]
@schellingb I think you added this feature a long time ago, maybe you know what is going on?

**Comment by CyberShadow** [comment]
It looks like `wxTextOutputStream` is not writing the space between the two numbers.

wxWidgets was recently updated in 9162f34860b71a38005d689ae342a1251e5ef4ba. Perhaps you can check if earlier versions have that problem?

**Comment by LHolten** [comment]
yes looks like that commit removed the space
