### ISSUE TITLE
issue building dr mingw

### ISSUE THREAD

**Issue by vtorri** [VerySleepy/verysleepy#82]
hello

win7, in cmd, i launch drmingw_build_mingw.cmd, but it fails with this error message:

```
E:\Documents\programmes_x64\msys2\home\vtorri\gitroot_64\verysleepy\thirdparty>drmingw_build_mingw.cmd
drmingw_build: Found 7-Zip at "C:\Program Files\7-Zip\7z.exe"
Downloading i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z...
Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « La connexion sous-jacente a été fermée : Une erreur inattendue s'est produite lors de l'envoi. »
Au niveau de ligne : 1 Caractère : 40
+ (New-Object Net.WebClient).DownloadFile <<<< ('https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.3.0/threads-win32/dwarf/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z/download', 'E:\Documents\programmes_x64\msys2\home\vtorri\gitroot_64\verysleepy\thirdparty\/mingw/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z')
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

```

can't you detect if mingw is installed ? Because I usually use msys2 + mingw and everything is already installed.

regards

**Comment by CyberShadow** [comment]
Looks like a temporary error, or maybe similar to https://github.com/VerySleepy/verysleepy/issues/49#issuecomment-850841571 . Can you try again?

> can't you detect if mingw is installed ? Because I usually use msys2 + mingw and everything is already installed.

Because of the constant API/ABI/compatibility churn/fragility of these components, it's difficult to make any assumptions about compatibility with any particular version other than the ones we explicitly test against. This is why all relevant dependencies are pinned and are obtained during the build process.

**Comment by vtorri** [comment]
i've tried several times, still the same error. Btw, appweyor build is failing with a similar issue

there are also newer mingw toolchain (8.1.0), maybe drmingw_build_mingw;cmd should be updated

**Comment by CyberShadow** [comment]
> Btw, appweyor build is failing with a similar issue

Yes, because at the time the sourceforge certificate was not valid, as per the comment I linked to.

> there are also newer mingw toolchain (8.1.0), maybe drmingw_build_mingw;cmd should be updated

Feel free to submit a PR doing so, but we rely on CI to validate changes and ensure basic functionality remains working. Though, if the CI is not working due to SourceForge / .NET connection issues, that would need to be fixed first...

**Comment by vtorri** [comment]
reopen (bad click...)

**Comment by CyberShadow** [comment]
> Btw, appweyor build is failing with a similar issue

And now it's not.

@vtorri If you are still getting that error, could you try this patch please: https://github.com/VerySleepy/verysleepy/commit/97f012391d879fb9322ec010006048dc5d63b456

**Comment by vtorri** [comment]
another error . It seems that Tls12 is not supported on my computer (win7 64 bits). The error says that Ssl3 or Tls should be used. Here is the error : 

```
Downloading i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z...
Exception lors de la définition de « SecurityProtocol » : « Impossible de convertir la valeur Null en type « System.Net.SecurityProtocolType » en raison de valeurs d'énumération non valides. Spécifiez l'une des valeurs d'énumération suivantes et réessayez. Les valeurs d'énumération possibles sont « Ssl3, Tls ». »
Au niveau de ligne : 1 Caractère : 28
+ [Net.ServicePointManager]:: <<<< SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12 ; (New-Object Net.WebClient).DownloadFile('https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.3.0/threads-win32/dwarf/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z/download', 'E:\Documents\programmes_x64\msys2\home\vtorri\gitroot_64\verysleepy\thirdparty\/mingw/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z')
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « La connexion sous-jacente a été fermée : Une erreur inattendue s'est produite lors de l'envoi. »
Au niveau de ligne : 1 Caractère : 129
+ [Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12 ; (New-Object Net.WebClient).DownloadFile <<<< ('https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.3.0/threads-win32/dwarf/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z/download', E:\Documents\programmes_x64\msys2\home\vtorri\gitroot_64\verysleepy\thirdparty\/mingw/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z')
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException 
```

**Comment by vtorri** [comment]
With Tls; i have only the 2nd error:

```
Downloading i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z...
Exception lors de l'appel de « DownloadFile » avec « 2 » argument(s) : « La connexion sous-jacente a été fermée : Une erreur inattendue s'est produite lors de l'envoi. »
Au niveau de ligne : 1 Caractère : 127
+ [Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls ; (New-Object Net.WebClient).DownloadFile <<<< ('https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.3.0/threads-win32/dwarf/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z/download', 'E:\Documents\programmes_x64\msys2\home\vtorri\gitroot_64\verysleepy\thirdparty\/mingw/i686-6.3.0-release-win32-dwarf-rt_v5-rev1.7z')
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException
```

**Comment by CyberShadow** [comment]
Generally, I don't think it's realistic for us to support building Very Sleepy on Windows versions which are no longer supported by Microsoft.

You could try deleting that line (or move it to the bottom) to let the script use another method for downloading files.

**Comment by vtorri** [comment]
fine, and closing
thanks
