### ISSUE TITLE
using libdwarf instead of dr mingw ?

### ISSUE THREAD

**Issue by vtorri** [VerySleepy/verysleepy#83]
Hello

there is a library, libdwarf, which can read dwarf  2, 3, 4, 5 symbols. I helped the developper to add the support of PE files compiled with dwarf symbols. Maybe this library can replace dr mingw

see https://github.com/davea42/libdwarf-code

**Comment by CyberShadow** [comment]
Dr. MinGW already uses libdwarf.

**Comment by vtorri** [comment]
then why using an application instead of the library if you just want stack frames ? It is also certainly simpler and faster to build than dr mingw

**Comment by CyberShadow** [comment]
We use the MgwHelp library, which is essentially a shim around libdwarf with the DbgHelp API. Please look at that project for more information about that project. The Very Sleepy issue tracker is also probably not the best place to ask questions about MgwHelp or Dr. MinGW,
