### ISSUE TITLE
Apply symbols at analyzing saved capture

### ISSUE THREAD

**Issue by birdy-spb** [VerySleepy/verysleepy#90]
Hi!

I have use-case:
1. save program calls at customer PC with performance issue to capture file
2. send capture file to development department
3. analyze saved capture at development environment with huge pdb files

May be I missed something... Is there any way to manage that with existing software?

**Comment by CyberShadow** [comment]
Yes, use the late symbol resolution feature, I added it for exactly this purpose :)

1. Make sure your program is built with external debug information (.pdb file).
2. On the customer's PC, enable the "Save minidump after ..." option.
3. Perform capture. The capture will include a minidump, which will have debug information needed to apply symbols.
4. On the developer PC, open the capture. Make sure the symbol paths are configured. Very Sleepy will use the minidump to load the correct symbols and apply them to the profiling information.

**Comment by CyberShadow** [comment]
I just remembered there is a wiki page:

https://github.com/VerySleepy/verysleepy/wiki/Late-Symbol-Resolution

**Comment by birdy-spb** [comment]
Wow! Thank you for immediate answer and cool software!
